In [2]:
# Read in cbb.csv:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

cbb = pd.read_csv('cbb.csv')

In [29]:
# make a new column called "SEASON_FINAL" that takes the column "POSTSEASON" and assigns a value: Champion = 1, 2nd = 2, etc.:
cbb['SEASON_FINAL'] = cbb['POSTSEASON'].replace(['Champions', '2ND', 'F4', 'E8', 'S16', 'R32', 'R64', 'R68', 'NaN'], [1, 2, 4, 8, 16, 32, 64, 68, 0])


# Sort by "SEASON_FINAL" and then by "YEAR":
cbb = cbb.sort_values(['YEAR', 'SEASON_FINAL'], ascending=[True, True])


# Count number of NaN and NA values in SEASON_FINAL column:
cbb['SEASON_FINAL'].isna().sum()
# Makee NaN values in SEASON_FINAL column equal to 0:
cbb['SEASON_FINAL'] = cbb['SEASON_FINAL'].fillna(0)

cbb['SEASON_FINAL'].isna().sum()

# show value count for "SEASON_FINAL" column:
cbb['SEASON_FINAL'].value_counts()

cbb.head(10)

,TEAM,CONF,G,W,ADJOE,ADJDE,BARTHAG,EFG_O,EFG_D,TOR,...,2P_O,2P_D,3P_O,3P_D,ADJ_T,WAB,POSTSEASON,SEED,YEAR,SEASON_FINAL
13,Louisville,BE,40,35,115.9,84.5,0.9743,50.6,44.8,18.3,...,50.8,43.4,33.3,31.8,67.1,9.0,Champions,1.0,2013,1.0
6,Michigan,B10,38,30,121.5,93.7,0.9522,54.6,48.0,14.6,...,53.4,47.6,37.9,32.6,64.8,6.2,2ND,4.0,2013,2.0
54,Syracuse,BE,40,30,113.0,87.0,0.9533,49.0,42.6,18.9,...,48.5,42.6,33.4,28.4,65.4,5.1,F4,4.0,2013,4.0
55,Wichita St.,MVC,39,30,110.6,91.0,0.9045,50.0,45.3,19.4,...,49.6,43.6,33.9,32.2,65.0,2.2,F4,9.0,2013,4.0
38,Ohio St.,B10,37,29,113.6,89.4,0.9406,50.6,45.4,16.2,...,49.4,43.6,35.6,32.4,65.3,7.2,E8,2.0,2013,8.0
39,Duke,ACC,36,30,118.4,91.5,0.9507,53.9,45.5,15.6,...,50.8,46.2,39.9,29.0,67.8,7.5,E8,2.0,2013,8.0
40,Marquette,BE,35,26,113.0,93.2,0.9020,49.6,46.2,20.9,...,51.6,44.9,29.6,32.3,64.6,4.5,E8,3.0,2013,8.0
41,Florida,SEC,37,29,115.7,85.7,0.9694,55.2,43.3,17.8,...,54.3,41.8,37.8,31.0,62.8,4.1,E8,3.0,2013,8.0
2447,Indiana,B10,36,29,121.0,89.7,0.9692,54.7,44.0,19.3,...,52.0,43.2,40.3,30.4,67.8,7.8,S16,1.0,2013,16.0
2448,Kansas,B12,37,31,111.6,86.2,0.9514,53.3,41.5,20.3,...,52.9,39.3,36.4,30.3,67.7,7.5,S16,1.0,2013,16.0

In [4]:
# Count number of teams per year:
cbb['YEAR'].value_counts().sort_index()

YEAR
2013    347
2014    351
2015    351
2016    351
2017    351
2018    351
2019    353
2021    347
2022    358
2023    363
Name: count, dtype: int64

In [23]:
# Read in 2020 data frrom cbb20.csv:
cbb20 = pd.read_csv('cbb20.csv')

cbb20.head(10)

,RK,TEAM,CONF,G,W,ADJOE,ADJDE,BARTHAG,EFG_O,EFG_D,...,ORB,DRB,FTR,FTRD,2P_O,2P_D,3P_O,3P_D,ADJ_T,WAB
0,1,Kansas,B12,30,28,116.1,87.7,0.9616,53.7,43.7,...,32.6,26.4,35.8,23.2,54.9,42.4,34.1,30.5,67.4,10.8
1,2,Baylor,B12,30,26,114.5,88.4,0.9513,49.4,45.2,...,35.8,29.8,30.8,30.8,47.5,44.4,35.1,31.1,66.2,8.5
2,3,Gonzaga,WCC,33,31,121.3,94.3,0.9472,57.5,47.6,...,33.6,22.7,38.8,21.8,57.4,47.4,38.6,32.0,72.0,7.7
3,4,Dayton,A10,31,29,119.5,93.4,0.9445,59.7,46.6,...,26.4,26.6,33.9,30.9,62.3,45.1,37.1,33.0,67.5,6.8
4,5,Michigan St.,B10,31,22,114.8,91.3,0.9326,52.6,43.3,...,32.8,26.0,30.8,29.3,52.9,43.4,34.8,28.7,69.3,5.2
5,6,Duke,ACC,31,25,115.3,91.9,0.9310,52.6,45.7,...,34.8,28.0,35.6,30.9,52.5,46.0,35.2,29.9,71.7,5.1
6,7,Creighton,BE,30,24,120.6,96.4,0.9289,55.2,48.4,...,23.9,30.2,28.8,23.4,53.0,48.9,38.7,31.8,68.3,6.1
7,8,Ohio St.,B10,31,21,114.6,92.6,0.9200,52.3,46.2,...,31.1,25.5,36.7,29.3,49.7,44.2,37.3,32.7,66.2,3.8
8,9,Louisville,ACC,31,24,115.1,93.9,0.9120,52.5,45.1,...,32.0,25.0,32.2,29.0,50.1,45.1,37.6,30.1,66.9,4.3
9,10,San Diego St.,MWC,31,30,113.8,92.8,0.9119,54.6,45.2,...,28.2,25.4,28.3,30.6,53.0,45.3,37.9,30.1,64.7,6.7

In [26]:
# Total teams in cbb20:
cbb20['TEAM'].count() # 353 teams in 2020

353

In [27]:
# List columns if cbb:
cbb.columns

Index(['TEAM', 'CONF', 'G', 'W', 'ADJOE', 'ADJDE', 'BARTHAG', 'EFG_O', 'EFG_D',
       'TOR', 'TORD', 'ORB', 'DRB', 'FTR', 'FTRD', '2P_O', '2P_D', '3P_O',
       '3P_D', 'ADJ_T', 'WAB', 'POSTSEASON', 'SEED', 'YEAR', 'SEASON_FINAL'],
      dtype='object')

In [28]:
# List columns of cbb20:
cbb20.columns

Index(['RK', 'TEAM', 'CONF', 'G', 'W', 'ADJOE', 'ADJDE', 'BARTHAG', 'EFG_O',
       'EFG_D', 'TOR', 'TORD', 'ORB', 'DRB', 'FTR', 'FTRD', '2P_O', '2P_D',
       '3P_O', '3P_D', 'ADJ_T', 'WAB'],
      dtype='object')

In [ ]:
# Changes to make to cbb20:

# New columns: YEAR (2020 for all), SEASON_FINAL (this will be what we predict)
# RK is specific to 2020 data, can be used for SEASON_FINAL OR the powerranking column BARTHAG can be used
# BARTHAG: Power Rating (Chance of beating an average Division I team)
# Both can be used for prediction, both have different results...
# Could also make a W/L ratio given the "G" column for games played and the "W" column for wins to predict SEASON_FINAL

In [ ]:
# TO DO:

# Determine what columns to keep for both in combined dataset:
    # YEAR, TEAM, CONF, G, W, BARTHAG, SEASON_FINAL (intially empty for 2020), POST_SEASON (initially empty for 2020)

# Make changes to 2020 data to match what columns we want to keep ("POSTSEASON" or "SEASONFINAL" columns)
# Append 2020 data to cbb data.

# Create an outline for what we want to do with this dataB